on:
push:
branches: [ "main"]
#dispara apenas ao realizar merge ou push na main

jobs:
build-and-push: 
runs-on: ubuntu-latest
-name: baixar codigo
uses: actions/checkout@v4
-name: configurar docker buildx
uses: docker/setup-buildx-actions@v3
-name: autenticar no docker hub
uses: docker/login-actions@v3
with:
username: ${{secrets.DOCKER_USERNAME}}
password: ${{secretes.DOCKER_PASSWORD}}
-name: extrair metadados do docker
id: meta
uses: docker/metadata-actions@v5
with:
images: ${{secrets.DOCKER_USERNAME}}/minha-aplicacao
tags:
 type=raw,value=latest
 type=sha,format=short
-name: construir e publicar imagem
uses: docker/build-push-action@v5
with:
context: .
push: true
tags: ${{steps.meta.outputs.tags}}
labels: ${{steps.meta.outputs.labels}}
